name: cow
description: ğŸ® Cow is just an humble AI in your terminal. ğŸ¥º
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  bloc: ^8.1.4
  blocterm:
    path: packages/blocterm
  cli_completion: ^0.5.1
  cow_brain:
    path: packages/cow_brain
  cow_model_manager:
    path: packages/cow_model_manager
  ffi: ^2.1.0
  io: ^1.0.4
  json_annotation: ^4.10.0
  llama_cpp_dart:
    path: packages/llama_cpp_dart
  logger: ^2.4.0
  logic_blocks:
    path: packages/logic_blocks
  meta: ^1.18.0
  mlx_dart:
    path: packages/mlx_dart
  nocterm: ^0.4.4
  path: ^1.9.1
  platform: ^3.1.5
  pub_updater: ^0.5.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.8.0
  build_verify: ^3.1.1
  build_version: ^2.1.3
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

executables:
  cow:
