name: cow_model_manager
description: Model installer + path management for Cow.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  clock: ^1.1.2
  http: ^1.2.2
  meta: ^1.18.0
  path: ^1.9.1
  platform: ^3.1.5

dev_dependencies:
  coverage: ^1.15.0
  test: ^1.29.0
  test_coverage_badge: ^0.3.2
