name: blocterm
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^8.1.4
  nocterm:
    path: /Users/joanna/Desktop/nocterm

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  test_coverage_badge: ^0.3.2
  very_good_analysis: ^10.0.0
