name: llama_cpp_dart
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.0
  hooks: ^1.0.0
  path: ^1.9.1

dev_dependencies:
  ffigen: ^18.0.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
